export const ACTION_TYPE_SET_FILTERS = 'SET_FILTERS';
export const ACTION_TYPE_VISIBLE_ADD_NEW_PRODUCT = 'VISIBLE_ADD_NEW_PRODUCT';
export const ACTION_TYPE_REMOVE = 'REMOVE';
export const ACTION_TYPE_EDIT = 'EDIT';
export const ACTION_TYPE_ADD = 'ADD';
